---
title: "CBB-Metadata_Apr28-2020"
author: "Sabah Ul-Hasan"
output: pdf_document
---
                Lines
Packages        13-49
Data            54-56
Piechart        58-82
Wordcloud       84-98
Barchart        100-125

Install Relevant Packages, Load Libraries 
```{r}

# Package installation
# Uncomment packages to re-install or update the versions
# Check version of R + RStudio when running into installation trouble

## Need package for downloading data directly from Github
### install.packages("RCurl") 
### packageVersion("RCurl") # v1.98.1.1 

## Need package for data clean-up (pipes)
### install.packages("dplyr") 
### packageVersion("dplyr") # v0.8.4

## Need package to create word clouds
### install_github("lchiffon/wordcloud2")
### packageVersion("wordcloud2") # v0.2.2

## Need package for visualization of data 
### install.packages("ggplot2") 
### packageVersion("ggplot2") # v3.3.0

## Need package to compile images as a unified figure
### install.packages("cowplot")
### packageVersion("cowplot") # v1.0.0



# Load libraries directly, if packages previously installed 
library(RCurl)
library(dplyr)
library(wordcloud2)
library(ggplot2)
library(cowplot) 

```

Visualizations
```{r}

# Upload Data 
df <- read.csv(text=getURL("https://raw.githubusercontent.com/SuLab/TSRI-CBB/master/CBB-Metadata/TSRI-CBB-Metadata_LastUpdated-Apr28-2020.csv")) 
summary(df) # Quick view of data

# Who is part of CBB?
# Pie chart of 'Position' column (n = 75)
## Pipe for data table of position vs frequency
pc <- df$Position %>% # column with word strings
  na.omit() %>% # gets rid of any empty row (na)
  as.character() %>% # converts all rows to character
  unlist() %>% # unlists
  table() %>% # converts to table
  sort(decreasing = TRUE) %>% # sorts by high to low freq
  data.frame() # converts to dataframe
## Create figure 
ggplot(pc, aes (x="", y = Freq, fill = .)) + 
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(label = paste(round(Freq / sum(Freq) * 100, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  theme_classic() +
  theme(plot.title = element_text(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Title",
       x = NULL,
       y = NULL) + 
  coord_polar("y")
ggsave("CBB-Position_piechart_Apr28-2020.png", dpi = 800) 

# What are the main topic interests of CBB?
# Word cloud of 'Topics' column
## Pipe for data table of word vs frequency
wc <- df$Topics %>% 
  na.omit() %>% 
  as.character() %>% 
  strsplit(" ") %>% 
  unlist() %>% 
  table() %>% 
  sort(decreasing = TRUE) %>% 
  data.frame()
## Create figure 
png("CBB-Topics_wordcloud_Apr28-2020.png")
wordcloud2(wc, size=1.6, color="random-light", backgroundColor="black", shape = "circle")
dev.off()

# What programming languages would CBB like to learn?
# Bar chart of programming languages known (Yes) vs interests
## Identify percentages for new dataframe of all languages
### (x/75)*100 # rounded-up
summary(df$Bash) # 39% yes, 17% interested
summary(df$R) # 55% yes, 24% interested
summary(df$Python) # 43% yes, 35% interested
summary(df$C..) # 11% yes, 15% interested
summary(df$JavaScript) # 8% yes, 11% interested
summary(df$TypeScript) # 3% yes, 0% interested
summary(df$Matlab) # 5% yes, 20% interested
summary(df$SAS) # 4% yes, 4% interested
## Create data frame based on the above
bc <- data.frame(
  Language = c("Bash","Bash","R","R","Python","Python","C++","C++","JavaScript","JavaScript","TypeScript","TypeScript","MATLAB","MATLAB","SAS","SAS"),
  Proficiency = rep(c("Yes" , "Interested"),8),
  Percentage = c(39,17,55,24,43,35,11,15,8,11,3,0,5,20,4,4)
)
## Create figure 
ggplot(data=bc, aes(x=Language, y=Percentage, fill=Proficiency)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=Percentage), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
ggsave("CBB-Proficiency_barchart_Apr28-2020.png", dpi = 800) 

```