---
title: "CBB-Metadata_Aug27-2021"
author: "Sabah Ul-Hasan"
output: pdf_document
---
                Lines
Packages        13-50
Data            52-147
  Piechart        61
  Wordclouds      87
  Barchart        119

Install Relevant Packages, Load Libraries 
```{r}

# Package installation
# Uncomment packages to re-install or update the versions
# Check version of R + RStudio when running into installation trouble

## Need package for downloading data directly from Github
### install.packages("RCurl") 
### packageVersion("RCurl") # v1.98.1.4

## Need package for data clean-up (pipes)
### install.packages("dplyr") 
### packageVersion("dplyr") # v1.0.7

## Need package to create word clouds
###  install.packages("devtools") # Need for using 'install_github'
### packageVersion("devtools") # v2.4.2
### install_github("lchiffon/wordcloud2")
### packageVersion("wordcloud2") # v0.2.2

## Need package for visualization of data 
### install.packages("ggplot2") 
### packageVersion("ggplot2") # v3.3.5

## Need package to compile images as a unified figure
### install.packages("cowplot")
### packageVersion("cowplot") # v1.1.1

# Load libraries directly, if packages previously installed 
library(RCurl)
library(dplyr)
library(devtools)
library(wordcloud2)
library(ggplot2)
library(cowplot) 

```

Visualizations
```{r}

# Upload Data 
df <- read.csv(text=getURL("https://raw.githubusercontent.com/SuLab/TSRI-CBB/main/CBB-Metadata/TSRI-CBB-Metadata_LastUpdated-Aug27-2021.csv")) 
summary(df) # Quick view of data

seminars <- read.csv(text=getURL("https://raw.githubusercontent.com/SuLab/TSRI-CBB/main/CBB-Metadata/TSRI-CBB-Seminars_Sep6-2021.csv"))

# Who is part of CBB?
# Pie chart of 'Position' column (n = 117)
## Pipe for data table of position vs frequency
pc <- df$Position %>% # column with word strings
  na.omit() %>% # gets rid of any empty row (na)
  as.character() %>% # converts all rows to character
  unlist() %>% # unlists
  table() %>% # converts to table
  sort(decreasing = TRUE) %>% # sorts by high to low freq
  data.frame() # converts to dataframe
## Create figure 
ggplot(pc, aes (x="", y = Freq, fill = .)) + 
  geom_bar(width = 1, stat = "identity") +
  geom_text(aes(label = paste(round(Freq / sum(Freq) * 100, 1), "%")),
            position = position_stack(vjust = 0.5)) +
  theme_classic() +
  theme(plot.title = element_text(),
        axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Title",
       x = NULL,
       y = NULL) + 
  coord_polar("y")
ggsave("CBB-Position_piechart_Aug27-2021.png", dpi = 800) 

# What are the main topic interests of CBB?
# Word cloud of 'Topics' column
## Pipe for data table of word vs frequency
wc <- df$Topics %>% 
  na.omit() %>% 
  as.character() %>% 
  strsplit(" ") %>% 
  unlist() %>% 
  table() %>% 
  sort(decreasing = TRUE) %>% 
  data.frame()
## Create figure 
png("CBB-Topics_wordcloud_Aug27-2021.png")
wordcloud2(wc, size=0.7, color="random-light", backgroundColor="black", shape = "circle") # adjust font size to ensure words fit
dev.off()

# What are the main seminar keywords of CBB?
# Word cloud of 'Topics' column
## Pipe for data table of word vs frequency
wc <- seminars$Keywords %>% 
  na.omit() %>% 
  as.character() %>% 
  strsplit(" ") %>% 
  unlist() %>% 
  table() %>% 
  sort(decreasing = TRUE) %>% 
  data.frame()
## Create figure 
png("CBB-Seminars_wordcloud_Sep7-2021.png")
wordcloud2(wc, size=0.7, color="random-light", backgroundColor="black", shape = "circle") # adjust font size to ensure words fit
dev.off()

# What programming languages would CBB like to learn?
# Bar chart of programming languages known (Yes) vs interests ('some' integrated as interests)
## Identify percentages for new dataframe of all languages
### (x/117)*100 # rounded-up
table(df$Bash) # 46% yes, 20% interested
table(df$R) # 56% yes, 26% interested
table(df$Python) # 51% yes, 32% interested
table(df$C..) # 11% yes, 15% interested
table(df$Java) # 1% yes, 0% interested
table(df$JavaScript) # 8% yes, 13% interested
table(df$TypeScript) # 3% yes, 2% interested
table(df$Matlab) # 7% yes, 21% interested
table(df$SAS) # 4% yes, 5% interested
## Create data frame based on the above
bc <- data.frame(
  Language = c("Bash","Bash","R","R","Python","Python","C++","C++","JavaScript","JavaScript", "MATLAB","MATLAB"), # remove any with low scores (less than 10% for both)
  Proficiency = rep(c("Yes" , "Interested"),6),
  Percentage = c(46,20,56,26,51,32,11,15,8,13,7,21)
)
## Create figure 
ggplot(data=bc, aes(x=Language, y=Percentage, fill=Proficiency)) +
  geom_bar(stat="identity", position=position_dodge())+
  geom_text(aes(label=Percentage), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)+
  scale_fill_brewer(palette="Paired")+
  theme_minimal()
ggsave("CBB-Proficiency_barchart_Aug27-2021.png", dpi = 800) 

```